Repository AyushMann29/GrabHack-Project-Nova, pull requests merged in 2025-10, with the labels that each got.

#2 UI improved with modern bubbles design
  __pycache__/main.cpython-312.pyc
  index.html
Labels: enhancement, Hacktoberfest

#6 added code of conduct. no code contribution
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, Hacktoberfest

#14 Add badges and license information to README for better visibility
  README.md
Labels: documentation, hacktoberfest-accepted

#16 Added a small blog about the project
  blog.html
  index.html
Labels: enhancement, hacktoberfest-accepted

#19 Fix: Add Vertical Scrollbar Support for Better UI Usability
  blog.html
  index.html
Labels: good first issue, Hacktoberfest

#29 Feat: Make "Powered by Grab" text clickable
  index.html
Labels: enhancement, hacktoberfest-accepted

#31 Added a Guideline Button
  index.html
Labels: enhancement, hacktoberfest-accepted

#30 Added Feedback form
  index.html
  main.py
Labels: hacktoberfest-accepted

#33 Enhanced UI
  index.html
Labels: enhancement, hacktoberfest-accepted

#36 Adding linkedIn Icon
  blog.html
Labels: hacktoberfest-accepted
